service: sales-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  createProduct:
    handler: handlers/product-handler.newProduct
    events:
      - http:
          path: product
          method: post

  updateProduct:
    handler: handlers/product-handler.updateProduct
    events:
      - http:
          path: product
          method: put

  product-qty-updater:
    name: product-qty-function
    handler: handlers/product-handler.updateProductQuantity
    events:
      - sns:
          arn: "arn:aws:sns:us-east-1:458929599444:product-amount-update-topic"

  createInvoice:
    name: create-invoice-function
    handler: handlers/invoice-handler.newInvoice
    events:
      - http:
          path: invoice
          method: post

  updateInvoice:
    name: update-invoice-function
    handler: handlers/invoice-handler.updateInvoice
    events:
      - http:
          path: invoice
          method: put


  removeInvoice:
    name: remove-invoice-function
    handler: handlers/invoice-handler.removeInvoice
    events:
      - http:
          path: invoice/{invoiceNumber}
          method: delete
          request:
            parameters:
              paths:
                invoiceNumber: true





custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001
  serverless-offline-sns:
    # port: 4004 # a free port for the sns server to run on
    debug: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-offline-sns
  - serverless-offline-direct-lambda