service: sales-service

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  createProduct:
    handler: handlers/product-handler.newProduct
    events:
      - http:
          path: product
          method: post

  updateProduct:
    handler: handlers/product-handler.updateProduct
    events:
      - http:
          path: product
          method: put

  product-qty-updater:
    handler: handlers/product-handler.updateProductQuantity
    events:
      - sns:
          arn: "arn:aws:sns:us-east-1:458929599444:product-amount-update-topic"


custom:
  serverless-offline-sns:
    port: 4004 # a free port for the sns server to run on
    debug: true

plugins:
  - serverless-offline
  - serverless-offline-sns