### New Invoice
POST http://localhost:4000/development/invoice
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "invoiceNumber": 123,
  "paid": 25,
  "remain": 5,
  "client": {
    "firstName": "mostafa",
    "lastName": "al",
    "email": "mostafa@gmail.com"
  },
  "items": [{
    "sku":"sku23",
    "title" : "",
    "quantity": 2,
    "costPrice":10,
    "salePrice": 15
  }]
}